// src/pages/finance/financelang.js

export const financeTranslations = {
    en: {
        // ── Common ────────────────────────────────────────────────
        'fin.common.refresh': 'Refresh',
        'fin.common.exportCsv': 'Export CSV',
        'fin.common.exportExcel': 'Export Excel',
        'fin.common.accessDenied': 'You do not have permission to view Finance.',
        'fin.common.noData': 'No data available for the selected period',
        'fin.common.noRecords': 'No records found',
        'fin.common.yes': 'Yes',
        'fin.common.no': 'No',

        // ── Filters ───────────────────────────────────────────────
        'fin.filter.range': 'Range',
        'fin.filter.thisWeek': 'This Week',
        'fin.filter.thisMonth': 'This Month',
        'fin.filter.thisYear': 'This Year',
        'fin.filter.custom': 'Custom',
        'fin.filter.from': 'From',
        'fin.filter.to': 'To',
        'fin.filter.granularity': 'Granularity',
        'fin.filter.auto': 'Auto',
        'fin.filter.daily': 'Daily',
        'fin.filter.weekly': 'Weekly',
        'fin.filter.monthly': 'Monthly',
        'fin.filter.status': 'Status',
        'fin.filter.all': 'All',

        // ── Statuses ──────────────────────────────────────────────
        'fin.status.pending': 'Pending',
        'fin.status.active': 'Active',
        'fin.status.inactive': 'Inactive',
        'fin.status.expired': 'Expired',
        'fin.status.cancelled': 'Cancelled',
        'fin.status.suspended': 'Suspended',
        'fin.status.accepted': 'Accepted',
        'fin.status.on_the_way': 'On The Way',
        'fin.status.arrived': 'Arrived',
        'fin.status.in_progress': 'In Progress',
        'fin.status.completed': 'Completed',
        'fin.status.rejected': 'Rejected',
        'fin.status.approved': 'Approved',

        // ── Layout tabs ───────────────────────────────────────────
        'fin.layout.subscriptions': 'Subscriptions',
        'fin.layout.technicians': 'Technicians',
        'fin.layout.customers': 'Customers',
        'fin.layout.requests': 'Requests',

        // ── Finance Customers ─────────────────────────────────────
        'fin.cust.stat.total': 'Total Customers',
        'fin.cust.stat.active': 'Active',
        'fin.cust.stat.pending': 'Pending',
        'fin.cust.stat.suspended': 'Suspended',
        'fin.cust.chart.dailyWeek': 'Daily Customer Signups (This Week)',
        'fin.cust.chart.dailyMonth': 'Daily Customer Signups (This Month)',
        'fin.cust.chart.dailyRange': 'Daily Customer Signups (Selected Range)',
        'fin.cust.chart.byStatus': 'By Status',
        'fin.cust.chart.trend': 'Signups Trend',
        'fin.cust.table.title': 'Customer Records',
        'fin.cust.table.searchPlaceholder': 'Search name/email...',
        'fin.cust.table.col.name': 'Name',
        'fin.cust.table.col.email': 'Email',
        'fin.cust.table.col.phone': 'Phone',
        'fin.cust.table.col.status': 'Status',
        'fin.cust.table.col.active': 'Active',
        'fin.cust.table.col.created': 'Created',
        'fin.cust.legend.signups': 'Signups',

        // ── Finance Requests ──────────────────────────────────────
        'fin.req.stat.total': 'Total Requests',
        'fin.req.stat.pending': 'Pending',
        'fin.req.stat.accepted': 'Accepted',
        'fin.req.stat.completed': 'Completed',
        'fin.req.chart.dailyWeek': 'Daily Requests (This Week)',
        'fin.req.chart.dailyMonth': 'Daily Requests (This Month)',
        'fin.req.chart.dailyRange': 'Daily Requests (Selected Range)',
        'fin.req.chart.byStatus': 'By Status',
        'fin.req.chart.trend': 'Requests Trend ({granularity})',
        'fin.req.table.title': 'Request Records',
        'fin.req.table.searchPlaceholder': 'Search customer / technician / service...',
        'fin.req.table.col.id': '#',
        'fin.req.table.col.customer': 'Customer',
        'fin.req.table.col.technician': 'Technician',
        'fin.req.table.col.service': 'Service',
        'fin.req.table.col.status': 'Status',
        'fin.req.table.col.created': 'Created',
        'fin.req.legend.requests': 'Requests',

        // ── Finance Subscriptions ─────────────────────────────────
        'fin.sub.stat.total': 'Total Subscriptions',
        'fin.sub.stat.active': 'Active',
        'fin.sub.stat.revenue': 'Revenue',
        'fin.sub.stat.expired': 'Expired',
        'fin.sub.chart.dailyWeek': 'Daily Subscriptions (This Week)',
        'fin.sub.chart.dailyMonth': 'Daily Subscriptions (This Month)',
        'fin.sub.chart.dailyRange': 'Daily Subscriptions (Selected Range)',
        'fin.sub.chart.byStatus': 'By Status',
        'fin.sub.chart.trend': 'Trend ({granularity})',
        'fin.sub.table.title': 'Subscription Records',
        'fin.sub.table.searchPlaceholder': 'Search user...',
        'fin.sub.table.col.user': 'User',
        'fin.sub.table.col.plan': 'Plan',
        'fin.sub.table.col.amount': 'Amount',
        'fin.sub.table.col.status': 'Status',
        'fin.sub.table.col.paymentMethod': 'Payment Method',
        'fin.sub.table.col.created': 'Created',
        'fin.sub.table.col.expiry': 'Expiry',
        'fin.sub.legend.subscriptions': 'Subscriptions',
        'fin.sub.legend.revenue': 'Revenue',
        'fin.sub.legend.count': 'Count',

        // ── Finance Technicians ───────────────────────────────────
        'fin.tech.stat.total': 'Total Technicians',
        'fin.tech.stat.approved': 'Approved',
        'fin.tech.stat.pending': 'Pending',
        'fin.tech.chart.dailyWeek': 'Daily Technician Registrations (This Week)',
        'fin.tech.chart.dailyMonth': 'Daily Technician Registrations (This Month)',
        'fin.tech.chart.dailyRange': 'Daily Technician Registrations (Selected Range)',
        'fin.tech.chart.byStatus': 'By Verification Status',
        'fin.tech.chart.trend': 'Registrations Trend ({granularity})',
        'fin.tech.table.title': 'Technician Records',
        'fin.tech.table.searchPlaceholder': 'Search name / area...',
        'fin.tech.table.col.name': 'Name',
        'fin.tech.table.col.area': 'Area',
        'fin.tech.table.col.rating': 'Rating',
        'fin.tech.table.col.status': 'Status',
        'fin.tech.table.col.created': 'Created',
        'fin.tech.legend.registrations': 'Registrations',

        // ── Toasts ────────────────────────────────────────────────
        'fin.toast.exportSuccess': 'Report exported successfully',
        'fin.toast.exportFailed': 'Export failed',
        'fin.toast.histogramFailed': 'Failed to load daily histogram data',
    },

    sw: {
        // ── Common ────────────────────────────────────────────────
        'fin.common.refresh': 'Onyesha Upya',
        'fin.common.exportCsv': 'Hamisha CSV',
        'fin.common.exportExcel': 'Hamisha Excel',
        'fin.common.accessDenied': 'Huna ruhusa kuona Fedha.',
        'fin.common.noData': 'Hakuna data kwa kipindi kilichochaguliwa',
        'fin.common.noRecords': 'Hakuna rekodi zilizopatikana',
        'fin.common.yes': 'Ndiyo',
        'fin.common.no': 'Hapana',

        // ── Filters ───────────────────────────────────────────────
        'fin.filter.range': 'Kipindi',
        'fin.filter.thisWeek': 'Wiki Hii',
        'fin.filter.thisMonth': 'Mwezi Huu',
        'fin.filter.thisYear': 'Mwaka Huu',
        'fin.filter.custom': 'Maalum',
        'fin.filter.from': 'Kutoka',
        'fin.filter.to': 'Hadi',
        'fin.filter.granularity': 'Uwazi',
        'fin.filter.auto': 'Otomatiki',
        'fin.filter.daily': 'Kila Siku',
        'fin.filter.weekly': 'Kila Wiki',
        'fin.filter.monthly': 'Kila Mwezi',
        'fin.filter.status': 'Hali',
        'fin.filter.all': 'Zote',

        // ── Statuses ──────────────────────────────────────────────
        'fin.status.pending': 'Inasubiri',
        'fin.status.active': 'Hai',
        'fin.status.inactive': 'Haipo',
        'fin.status.expired': 'Imekwisha',
        'fin.status.cancelled': 'Imefutwa',
        'fin.status.suspended': 'Imesimamishwa',
        'fin.status.accepted': 'Imekubaliwa',
        'fin.status.on_the_way': 'Njiani',
        'fin.status.arrived': 'Amefika',
        'fin.status.in_progress': 'Inaendelea',
        'fin.status.completed': 'Imekamilika',
        'fin.status.rejected': 'Imekataliwa',
        'fin.status.approved': 'Imeidhinishwa',

        // ── Layout tabs ───────────────────────────────────────────
        'fin.layout.subscriptions': 'Usajili',
        'fin.layout.technicians': 'Mafundi',
        'fin.layout.customers': 'Wateja',
        'fin.layout.requests': 'Maombi',

        // ── Finance Customers ─────────────────────────────────────
        'fin.cust.stat.total': 'Jumla ya Wateja',
        'fin.cust.stat.active': 'Hai',
        'fin.cust.stat.pending': 'Inasubiri',
        'fin.cust.stat.suspended': 'Imesimamishwa',
        'fin.cust.chart.dailyWeek': 'Usajili wa Wateja kwa Siku (Wiki Hii)',
        'fin.cust.chart.dailyMonth': 'Usajili wa Wateja kwa Siku (Mwezi Huu)',
        'fin.cust.chart.dailyRange': 'Usajili wa Wateja kwa Siku (Kipindi Kilichochaguliwa)',
        'fin.cust.chart.byStatus': 'Kwa Hali',
        'fin.cust.chart.trend': 'Mwelekeo wa Usajili',
        'fin.cust.table.title': 'Rekodi za Wateja',
        'fin.cust.table.searchPlaceholder': 'Tafuta jina/barua pepe...',
        'fin.cust.table.col.name': 'Jina',
        'fin.cust.table.col.email': 'Barua Pepe',
        'fin.cust.table.col.phone': 'Simu',
        'fin.cust.table.col.status': 'Hali',
        'fin.cust.table.col.active': 'Hai',
        'fin.cust.table.col.created': 'Imeundwa',
        'fin.cust.legend.signups': 'Usajili',

        // ── Finance Requests ──────────────────────────────────────
        'fin.req.stat.total': 'Jumla ya Maombi',
        'fin.req.stat.pending': 'Inasubiri',
        'fin.req.stat.accepted': 'Imekubaliwa',
        'fin.req.stat.completed': 'Imekamilika',
        'fin.req.chart.dailyWeek': 'Maombi kwa Siku (Wiki Hii)',
        'fin.req.chart.dailyMonth': 'Maombi kwa Siku (Mwezi Huu)',
        'fin.req.chart.dailyRange': 'Maombi kwa Siku (Kipindi Kilichochaguliwa)',
        'fin.req.chart.byStatus': 'Kwa Hali',
        'fin.req.chart.trend': 'Mwelekeo wa Maombi ({granularity})',
        'fin.req.table.title': 'Rekodi za Maombi',
        'fin.req.table.searchPlaceholder': 'Tafuta mteja / fundi / huduma...',
        'fin.req.table.col.id': '#',
        'fin.req.table.col.customer': 'Mteja',
        'fin.req.table.col.technician': 'Fundi',
        'fin.req.table.col.service': 'Huduma',
        'fin.req.table.col.status': 'Hali',
        'fin.req.table.col.created': 'Imeundwa',
        'fin.req.legend.requests': 'Maombi',

        // ── Finance Subscriptions ─────────────────────────────────
        'fin.sub.stat.total': 'Jumla ya Usajili',
        'fin.sub.stat.active': 'Hai',
        'fin.sub.stat.revenue': 'Mapato',
        'fin.sub.stat.expired': 'Imekwisha',
        'fin.sub.chart.dailyWeek': 'Usajili kwa Siku (Wiki Hii)',
        'fin.sub.chart.dailyMonth': 'Usajili kwa Siku (Mwezi Huu)',
        'fin.sub.chart.dailyRange': 'Usajili kwa Siku (Kipindi Kilichochaguliwa)',
        'fin.sub.chart.byStatus': 'Kwa Hali',
        'fin.sub.chart.trend': 'Mwelekeo ({granularity})',
        'fin.sub.table.title': 'Rekodi za Usajili',
        'fin.sub.table.searchPlaceholder': 'Tafuta mtumiaji...',
        'fin.sub.table.col.user': 'Mtumiaji',
        'fin.sub.table.col.plan': 'Mpango',
        'fin.sub.table.col.amount': 'Kiasi',
        'fin.sub.table.col.status': 'Hali',
        'fin.sub.table.col.paymentMethod': 'Njia ya Malipo',
        'fin.sub.table.col.created': 'Imeundwa',
        'fin.sub.table.col.expiry': 'Kuisha',
        'fin.sub.legend.subscriptions': 'Usajili',
        'fin.sub.legend.revenue': 'Mapato',
        'fin.sub.legend.count': 'Idadi',

        // ── Finance Technicians ───────────────────────────────────
        'fin.tech.stat.total': 'Jumla ya Mafundi',
        'fin.tech.stat.approved': 'Imeidhinishwa',
        'fin.tech.stat.pending': 'Inasubiri',
        'fin.tech.chart.dailyWeek': 'Usajili wa Mafundi kwa Siku (Wiki Hii)',
        'fin.tech.chart.dailyMonth': 'Usajili wa Mafundi kwa Siku (Mwezi Huu)',
        'fin.tech.chart.dailyRange': 'Usajili wa Mafundi kwa Siku (Kipindi Kilichochaguliwa)',
        'fin.tech.chart.byStatus': 'Kwa Hali ya Uthibitisho',
        'fin.tech.chart.trend': 'Mwelekeo wa Usajili ({granularity})',
        'fin.tech.table.title': 'Rekodi za Mafundi',
        'fin.tech.table.searchPlaceholder': 'Tafuta jina / eneo...',
        'fin.tech.table.col.name': 'Jina',
        'fin.tech.table.col.area': 'Eneo',
        'fin.tech.table.col.rating': 'Kiwango',
        'fin.tech.table.col.status': 'Hali',
        'fin.tech.table.col.created': 'Imeundwa',
        'fin.tech.legend.registrations': 'Usajili',

        // ── Toasts ────────────────────────────────────────────────
        'fin.toast.exportSuccess': 'Ripoti imehamishwa kwa mafanikio',
        'fin.toast.exportFailed': 'Uhamishaji umeshindikana',
        'fin.toast.histogramFailed': 'Imeshindwa kupakia data ya histogram ya kila siku',
    },
};

export function tFin(language, key, replacements) {
    let str =
        financeTranslations[language]?.[key] ||
        financeTranslations.en?.[key] ||
        key;
    if (replacements) {
        Object.entries(replacements).forEach(([k, v]) => {
            str = str.replace(new RegExp(`\\{${k}\\}`, 'g'), v);
        });
    }
    return str;
}