// src/pages/users/userlang.js

export const userTranslations = {
    en: {
        'user.title': 'User Management',
        'user.subtitle': 'Manage accounts, roles and verification status',
        'user.add': 'Add User',
        'user.refresh': 'Refresh',
        'user.searchPlaceholder': 'Search name, email, phone…',
        'user.showDeleted': 'Show Deleted',
        'user.accessDenied': 'You do not have permission to view users.',
        'user.retry': 'Retry',
        'user.noFound': 'No users found',
        'user.noDeletedFound': 'No deleted users found',
        'user.cancel': 'Cancel',
        'user.confirm': 'Confirm',
        'user.actionFailed': 'Action failed',
        'user.actionSuccess': 'Action completed successfully',

        // Filters
        'user.filter.status': 'Status',
        'user.filter.allStatuses': 'All statuses',
        'user.filter.role': 'Role',
        'user.filter.allRoles': 'All roles',
        'user.status.active': 'Active',
        'user.status.inactive': 'Inactive',
        'user.status.pending': 'Pending',
        'user.status.suspended': 'Suspended',
        'user.status.deleted': 'Deleted',
        'user.role.admin': 'Administrator',
        'user.role.manager': 'Manager',
        'user.role.monitoring': 'Monitoring Officer',
        'user.role.fundi': 'Fundi',
        'user.role.customer': 'Customer',
        'user.role.user': 'User',

        // Table
        'user.col.user': 'User',
        'user.col.email': 'Email',
        'user.col.phone': 'Phone',
        'user.col.role': 'Role',
        'user.col.status': 'Status',
        'user.col.subscription': 'Subscription',
        'user.col.created': 'Created',
        'user.col.actions': 'Actions',
        'user.joined': 'Joined',
        'user.sub.active': 'Active',
        'user.sub.inactive': 'Inactive',
        'user.sub.expired': 'Expired',
        'user.sub.pending': 'Pending',
        'user.sub.daysLeft': 'd left',

        // Actions
        'user.action.edit': 'Edit',
        'user.action.activate': 'Activate',
        'user.action.deactivate': 'Deactivate',
        'user.action.suspend': 'Suspend',
        'user.action.delete': 'Delete',
        'user.action.resetPassword': 'Reset Password',
        'user.action.verifyOtp': 'Verify OTP',
        'user.action.markVerified': 'Mark as Verified',
        'user.action.resendOtp': 'Resend OTP',
        'user.action.restore': 'Restore',
        'user.action.forceDelete': 'Permanently Delete',

        // Confirm dialogs
        'user.confirm.restoreTitle': 'Restore User',
        'user.confirm.restoreMsg': 'Are you sure you want to restore {name}?',
        'user.confirm.forceDeleteTitle': 'Permanently Delete User',
        'user.confirm.forceDeleteMsg': 'Are you sure you want to permanently delete {name}?',
        'user.confirm.deactivateTitle': 'Deactivate User',
        'user.confirm.deactivateMsg': 'Are you sure you want to deactivate {name}?',
        'user.confirm.suspendTitle': 'Suspend User',
        'user.confirm.suspendMsg': 'Are you sure you want to suspend {name}?',
        'user.confirm.deleteTitle': 'Delete User',
        'user.confirm.deleteMsg': 'Are you sure you want to delete {name}?',
        'user.confirm.markVerifiedTitle': 'Mark as Verified',
        'user.confirm.markVerifiedMsg': 'Are you sure you want to mark {name} as verified without OTP? This will activate the account immediately.',

        // Success / error messages
        'user.msg.restored': 'User restored successfully',
        'user.msg.forceDeleted': 'User permanently deleted',
        'user.msg.activated': 'User activated successfully',
        'user.msg.otpSent': 'OTP sent successfully',
        'user.msg.verified': 'User marked as verified successfully',
        'user.msg.verifySuccess': 'User verified and activated successfully',
        'user.msg.passwordReset': 'Password reset successfully',
        'user.msg.loadDeletedFailed': 'Failed to load deleted users',
        'user.msg.restoreFailed': 'Failed to restore user',
        'user.msg.forceDeleteFailed': 'Failed to permanently delete user',
        'user.msg.activateFailed': 'Failed to activate user',
        'user.msg.otpFailed': 'Failed to send OTP',
        'user.msg.verifyFailed': 'Failed to mark user as verified',
        'user.msg.otpInvalid': 'Please enter a valid 6-digit OTP',
        'user.msg.passwordShort': 'Password must be at least 8 characters',
        'user.msg.passwordMismatch': 'Passwords do not match',
        'user.msg.passwordResetFailed': 'Failed to reset password',

        // Password dialog
        'user.pwd.title': 'Reset Password for {name}',
        'user.pwd.new': 'New Password',
        'user.pwd.confirm': 'Confirm Password',
        'user.pwd.submit': 'Reset Password',

        // OTP dialog
        'user.otp.title': 'Verify OTP for {name}',
        'user.otp.hint': "Enter the 6-digit OTP sent to the user's email/phone.",
        'user.otp.label': 'OTP Code',
        'user.otp.placeholder': 'Enter 6-digit OTP',
        'user.otp.submit': 'Verify OTP',

        // Form modal
        'user.form.editTitle': 'Edit User',
        'user.form.createTitle': 'Add New User',
        'user.form.editDesc': 'Update user details and role',
        'user.form.createDesc': 'Create a new account with role and credentials',
        'user.form.name': 'Full Name',
        'user.form.email': 'Email',
        'user.form.emailLocked': 'Email cannot be changed',
        'user.form.phone': 'Phone',
        'user.form.phoneOptional': 'Optional',
        'user.form.role': 'Role',
        'user.form.selectRole': 'Select Role',
        'user.form.loadingRoles': 'Loading roles…',
        'user.form.noRoles': 'No roles available',
        'user.form.password': 'Password',
        'user.form.passwordMin': 'Minimum 8 characters',
        'user.form.confirmPassword': 'Confirm Password',
        'user.form.status': 'Status',
        'user.form.update': 'Update User',
        'user.form.create': 'Create User',
        'user.form.updated': 'User updated successfully',
        'user.form.created': 'User created successfully',
        'user.form.failed': 'Operation failed',
        'user.form.checkErrors': 'Please check the form for errors.',
        'user.form.nameRequired': 'Name is required',
        'user.form.emailRequired': 'Email is required',
        'user.form.roleRequired': 'Role is required',
        'user.form.passwordRequired': 'Password is required',
    },
    sw: {
        'user.title': 'Usimamizi wa Watumiaji',
        'user.subtitle': 'Simamia akaunti, majukumu na hali ya uthibitishaji',
        'user.add': 'Ongeza Mtumiaji',
        'user.refresh': 'Onyesha Upya',
        'user.searchPlaceholder': 'Tafuta jina, barua pepe, simu…',
        'user.showDeleted': 'Onyesha Waliofutwa',
        'user.accessDenied': 'Huna ruhusa ya kuona watumiaji.',
        'user.retry': 'Jaribu Tena',
        'user.noFound': 'Hakuna watumiaji walipatikana',
        'user.noDeletedFound': 'Hakuna watumiaji waliofutwa',
        'user.cancel': 'Ghairi',
        'user.confirm': 'Thibitisha',
        'user.actionFailed': 'Kitendo kimeshindikana',
        'user.actionSuccess': 'Kitendo kimekamilika kwa mafanikio',

        // Filters
        'user.filter.status': 'Hali',
        'user.filter.allStatuses': 'Hali zote',
        'user.filter.role': 'Jukumu',
        'user.filter.allRoles': 'Majukumu yote',
        'user.status.active': 'Hai',
        'user.status.inactive': 'Haipo',
        'user.status.pending': 'Inasubiri',
        'user.status.suspended': 'Imesimamishwa',
        'user.status.deleted': 'Imefutwa',
        'user.role.admin': 'Msimamizi',
        'user.role.manager': 'Meneja',
        'user.role.monitoring': 'Afisa Ufuatiliaji',
        'user.role.fundi': 'Fundi',
        'user.role.customer': 'Mteja',
        'user.role.user': 'Mtumiaji',

        // Table
        'user.col.user': 'Mtumiaji',
        'user.col.email': 'Barua Pepe',
        'user.col.phone': 'Simu',
        'user.col.role': 'Jukumu',
        'user.col.status': 'Hali',
        'user.col.subscription': 'Usajili',
        'user.col.created': 'Imeundwa',
        'user.col.actions': 'Vitendo',
        'user.joined': 'Alijiunga',
        'user.sub.active': 'Hai',
        'user.sub.inactive': 'Haipo',
        'user.sub.expired': 'Imekwisha',
        'user.sub.pending': 'Inasubiri',
        'user.sub.daysLeft': 'siku zimebaki',

        // Actions
        'user.action.edit': 'Hariri',
        'user.action.activate': 'Washa',
        'user.action.deactivate': 'Zima',
        'user.action.suspend': 'Simamisha',
        'user.action.delete': 'Futa',
        'user.action.resetPassword': 'Weka Upya Nenosiri',
        'user.action.verifyOtp': 'Thibitisha OTP',
        'user.action.markVerified': 'Weka kama Imethibitishwa',
        'user.action.resendOtp': 'Tuma OTP Tena',
        'user.action.restore': 'Rejesha',
        'user.action.forceDelete': 'Futa Kabisa',

        // Confirm dialogs
        'user.confirm.restoreTitle': 'Rejesha Mtumiaji',
        'user.confirm.restoreMsg': 'Una uhakika unataka kurejesha {name}?',
        'user.confirm.forceDeleteTitle': 'Futa Mtumiaji Kabisa',
        'user.confirm.forceDeleteMsg': 'Una uhakika unataka kufuta kabisa {name}?',
        'user.confirm.deactivateTitle': 'Zima Mtumiaji',
        'user.confirm.deactivateMsg': 'Una uhakika unataka kuzima {name}?',
        'user.confirm.suspendTitle': 'Simamisha Mtumiaji',
        'user.confirm.suspendMsg': 'Una uhakika unataka kusimamisha {name}?',
        'user.confirm.deleteTitle': 'Futa Mtumiaji',
        'user.confirm.deleteMsg': 'Una uhakika unataka kufuta {name}?',
        'user.confirm.markVerifiedTitle': 'Weka kama Imethibitishwa',
        'user.confirm.markVerifiedMsg': 'Una uhakika unataka kuweka {name} kama imethibitishwa bila OTP? Hii itawasha akaunti mara moja.',

        // Success / error messages
        'user.msg.restored': 'Mtumiaji amerudishwa kwa mafanikio',
        'user.msg.forceDeleted': 'Mtumiaji amefutwa kabisa',
        'user.msg.activated': 'Mtumiaji amewashwa kwa mafanikio',
        'user.msg.otpSent': 'OTP imetumwa kwa mafanikio',
        'user.msg.verified': 'Mtumiaji amewekwa kama imethibitishwa',
        'user.msg.verifySuccess': 'Mtumiaji amethibitishwa na kuwashwa',
        'user.msg.passwordReset': 'Nenosiri limewekwa upya',
        'user.msg.loadDeletedFailed': 'Imeshindwa kupakia watumiaji waliofutwa',
        'user.msg.restoreFailed': 'Imeshindwa kurejesha mtumiaji',
        'user.msg.forceDeleteFailed': 'Imeshindwa kufuta kabisa mtumiaji',
        'user.msg.activateFailed': 'Imeshindwa kuwasha mtumiaji',
        'user.msg.otpFailed': 'Imeshindwa kutuma OTP',
        'user.msg.verifyFailed': 'Imeshindwa kuweka mtumiaji kama imethibitishwa',
        'user.msg.otpInvalid': 'Tafadhali weka OTP ya tarakimu 6',
        'user.msg.passwordShort': 'Nenosiri lazima liwe na angalau herufi 8',
        'user.msg.passwordMismatch': 'Nenosiri hazilingani',
        'user.msg.passwordResetFailed': 'Imeshindwa kuweka upya nenosiri',

        // Password dialog
        'user.pwd.title': 'Weka Upya Nenosiri la {name}',
        'user.pwd.new': 'Nenosiri Jipya',
        'user.pwd.confirm': 'Thibitisha Nenosiri',
        'user.pwd.submit': 'Weka Upya Nenosiri',

        // OTP dialog
        'user.otp.title': 'Thibitisha OTP ya {name}',
        'user.otp.hint': 'Weka OTP ya tarakimu 6 iliyotumwa kwa barua pepe/simu ya mtumiaji.',
        'user.otp.label': 'Nambari ya OTP',
        'user.otp.placeholder': 'Weka OTP ya tarakimu 6',
        'user.otp.submit': 'Thibitisha OTP',

        // Form modal
        'user.form.editTitle': 'Hariri Mtumiaji',
        'user.form.createTitle': 'Ongeza Mtumiaji Mpya',
        'user.form.editDesc': 'Sasisha maelezo ya mtumiaji na jukumu',
        'user.form.createDesc': 'Unda akaunti mpya yenye jukumu na hati',
        'user.form.name': 'Jina Kamili',
        'user.form.email': 'Barua Pepe',
        'user.form.emailLocked': 'Barua pepe haiwezi kubadilishwa',
        'user.form.phone': 'Simu',
        'user.form.phoneOptional': 'Si lazima',
        'user.form.role': 'Jukumu',
        'user.form.selectRole': 'Chagua Jukumu',
        'user.form.loadingRoles': 'Inapakia majukumu…',
        'user.form.noRoles': 'Hakuna majukumu yaliyopo',
        'user.form.password': 'Nenosiri',
        'user.form.passwordMin': 'Angalau herufi 8',
        'user.form.confirmPassword': 'Thibitisha Nenosiri',
        'user.form.status': 'Hali',
        'user.form.update': 'Sasisha Mtumiaji',
        'user.form.create': 'Unda Mtumiaji',
        'user.form.updated': 'Mtumiaji amesasishwa kwa mafanikio',
        'user.form.created': 'Mtumiaji ameundwa kwa mafanikio',
        'user.form.failed': 'Operesheni imeshindikana',
        'user.form.checkErrors': 'Tafadhali angalia fomu kwa makosa.',
        'user.form.nameRequired': 'Jina linahitajika',
        'user.form.emailRequired': 'Barua pepe inahitajika',
        'user.form.roleRequired': 'Jukumu linahitajika',
        'user.form.passwordRequired': 'Nenosiri linahitajika',
    },
};

export function tUser(language, key) {
    return (
        userTranslations[language]?.[key] ||
        userTranslations.en?.[key] ||
        key
    );
}