// src/pages/subscriptions/subscriptionslang.js

export const subscriptionTranslations = {
    en: {
        // ── Common ────────────────────────────────────────────────
        'sub.common.cancel': 'Cancel',
        'sub.common.confirm': 'Confirm',
        'sub.common.close': 'Close',
        'sub.common.delete': 'Delete',
        'sub.common.deleting': 'Deleting…',
        'sub.common.update': 'Update',
        'sub.common.create': 'Create',
        'sub.common.edit': 'Edit',
        'sub.common.active': 'Active',
        'sub.common.inactive': 'Inactive',
        'sub.common.areYouSure': 'Are you sure?',
        'sub.common.cannotUndo': 'This action cannot be undone.',
        'sub.common.actions': 'Actions',
        'sub.common.status': 'Status',
        'sub.common.name': 'Name',
        'sub.common.phone': 'Phone',
        'sub.common.order': 'Order',
        'sub.common.search': 'Search',
        'sub.common.refresh': 'Refresh',
        'sub.common.all': 'All',

        // ── Payment Methods ───────────────────────────────────────
        'sub.pm.accessDenied': 'You need permission to manage payment methods.',
        'sub.pm.title': 'Payment Methods',
        'sub.pm.subtitle': 'Manage payment options available to users',
        'sub.pm.totalMethods': 'Total Methods',
        'sub.pm.active': 'Active',
        'sub.pm.inactive': 'Inactive',
        'sub.pm.searchPlaceholder': 'Search methods…',
        'sub.pm.addMethod': 'Add Method',
        'sub.pm.col.logo': 'Logo',
        'sub.pm.col.name': 'Name',
        'sub.pm.col.phone': 'Phone',
        'sub.pm.col.account': 'Account',
        'sub.pm.col.status': 'Status',
        'sub.pm.col.order': 'Order',
        'sub.pm.col.actions': 'Actions',
        'sub.pm.noMatch': 'No payment methods match your search',
        'sub.pm.noFound': 'No payment methods found',
        'sub.pm.editTooltip': 'Edit',
        'sub.pm.deleteTooltip': 'Delete',
        'sub.pm.form.editTitle': 'Edit Payment Method',
        'sub.pm.form.createTitle': 'Create New Payment Method',
        'sub.pm.form.editDesc': 'Update payment method details',
        'sub.pm.form.createDesc': 'Add a new payment option',
        'sub.pm.form.name': 'Name *',
        'sub.pm.form.phoneNumber': 'Phone Number *',
        'sub.pm.form.accountName': 'Account Name',
        'sub.pm.form.displayOrder': 'Display Order',
        'sub.pm.form.uploadLogo': 'Upload Logo',
        'sub.pm.form.logoSelected': 'selected',
        'sub.pm.delete.title': 'Delete Payment Method',
        'sub.pm.delete.aboutTo': 'You are about to delete the payment method:',
        'sub.pm.delete.warning': 'All data related to this payment method will be permanently removed.',

        // ── Rate Cards ────────────────────────────────────────────
        'sub.rc.accessDenied': 'You need permission to manage rate cards.',
        'sub.rc.title': 'Rate Cards',
        'sub.rc.subtitle': 'Manage subscription plans and pricing',
        'sub.rc.totalCards': 'Total Rate Cards',
        'sub.rc.active': 'Active',
        'sub.rc.inactive': 'Inactive',
        'sub.rc.searchPlaceholder': 'Search rate cards…',
        'sub.rc.addCard': 'Add Rate Card',
        'sub.rc.col.name': 'Name',
        'sub.rc.col.price': 'Price',
        'sub.rc.col.duration': 'Duration',
        'sub.rc.col.currency': 'Currency',
        'sub.rc.col.status': 'Status',
        'sub.rc.col.order': 'Order',
        'sub.rc.col.actions': 'Actions',
        'sub.rc.days': 'days',
        'sub.rc.noMatch': 'No rate cards match your search',
        'sub.rc.noFound': 'No rate cards found',
        'sub.rc.editTooltip': 'Edit',
        'sub.rc.deleteTooltip': 'Delete',
        'sub.rc.form.editTitle': 'Edit Rate Card',
        'sub.rc.form.createTitle': 'Create New Rate Card',
        'sub.rc.form.editDesc': 'Update plan details',
        'sub.rc.form.createDesc': 'Define a new subscription plan',
        'sub.rc.form.name': 'Name *',
        'sub.rc.form.price': 'Price *',
        'sub.rc.form.currency': 'Currency *',
        'sub.rc.form.duration': 'Duration (days) *',
        'sub.rc.form.description': 'Description',
        'sub.rc.form.displayOrder': 'Display Order',
        'sub.rc.form.active': 'Active',
        'sub.rc.delete.title': 'Delete Rate Card',
        'sub.rc.delete.aboutTo': 'You are about to delete the rate card:',
        'sub.rc.delete.warning': 'All data related to this rate card will be permanently removed.',

        // ── Subscription List ─────────────────────────────────────
        'sub.list.accessDenied': 'You do not have permission.',
        'sub.list.title': 'Subscriptions',
        'sub.list.subtitle': 'Manage and approve user subscriptions',
        'sub.list.pending': 'Pending',
        'sub.list.active': 'Active',
        'sub.list.expired': 'Expired',
        'sub.list.cancelled': 'Cancelled',
        'sub.list.searchPlaceholder': 'Search…',
        'sub.list.filters': 'Filters',
        'sub.list.dateFrom': 'Date From',
        'sub.list.dateTo': 'Date To',
        'sub.list.apply': 'Apply',
        'sub.list.clear': 'Clear',
        'sub.list.noFound': 'No subscriptions found',
        'sub.list.col.user': 'User',
        'sub.list.col.plan': 'Plan',
        'sub.list.col.amount': 'Amount',
        'sub.list.col.status': 'Status',
        'sub.list.col.paymentMethod': 'Payment Method',
        'sub.list.col.reference': 'Reference',
        'sub.list.col.date': 'Date',
        'sub.list.col.expiry': 'Expiry',
        'sub.list.col.actions': 'Actions',
        'sub.list.status.pending': 'Pending',
        'sub.list.status.active': 'Active',
        'sub.list.status.expired': 'Expired',
        'sub.list.status.cancelled': 'Cancelled',
        'sub.list.export.csv': 'CSV',
        'sub.list.export.pdf': 'PDF',
        'sub.list.export.excel': 'Excel',

        // Messages
        'sub.list.msg.loadFailed': 'Failed to load subscriptions',
        'sub.list.msg.noInvoice': 'No invoice available',
        'sub.list.msg.invoiceDownloaded': 'Invoice downloaded successfully',
        'sub.list.msg.invoiceOpened': 'Invoice opened in new tab',
        'sub.list.msg.invoiceFailed': 'Failed to download invoice',
        'sub.list.msg.approved': 'Subscription #{id} approved successfully!',
        'sub.list.msg.approveFailed': 'Approval failed: {msg}',
        'sub.list.msg.rejected': 'Subscription #{id} rejected',
        'sub.list.msg.rejectFailed': 'Rejection failed',

        // Actions
        'sub.list.action.approve': 'Approve',
        'sub.list.action.reject': 'Reject',
        'sub.list.action.viewDetails': 'View Details',
        'sub.list.action.downloadInvoice': 'Download Invoice',
        'sub.list.action.invoice': 'Invoice',
        'sub.list.action.details': 'Details',

        // Reject dialog
        'sub.list.reject.title': 'Reject Subscription',
        'sub.list.reject.reason': 'Reason (optional)',
        'sub.list.reject.placeholder': 'Enter reason for rejection…',

        // Approve dialog
        'sub.list.approve.confirmTitle': 'Confirm Approval',
        'sub.list.approve.successTitle': 'Approved Successfully!',
        'sub.list.approve.errorTitle': 'Approval Failed',
        'sub.list.approve.subscriptionNo': 'Subscription #{id}',
        'sub.list.approve.infoAlert': 'You are about to approve this subscription. The user will gain access immediately.',
        'sub.list.approve.unknownUser': 'Unknown User',
        'sub.list.approve.noEmail': 'No email',
        'sub.list.approve.plan': 'Plan',
        'sub.list.approve.amount': 'Amount',
        'sub.list.approve.paymentMethod': 'Payment Method',
        'sub.list.approve.reference': 'Reference',
        'sub.list.approve.processing': 'Processing…',
        'sub.list.approve.complete': 'Complete!',
        'sub.list.approve.confirmBtn': 'Confirm Approve',
        'sub.list.approve.doneBtn': 'Done',
        'sub.list.approve.retryBtn': 'Retry',
        'sub.list.approve.validating': 'Validating subscription...',
        'sub.list.approve.processingPayment': 'Processing payment confirmation...',
        'sub.list.approve.updatingStatus': 'Updating subscription status...',
        'sub.list.approve.generatingInvoice': 'Generating invoice...',
        'sub.list.approve.sendingNotification': 'Sending notification...',
        'sub.list.approve.successMsg': '{name} can now access all features.',
        'sub.list.approve.errorDefault': 'An error occurred while approving the subscription.',

        // View details dialog
        'sub.list.view.title': 'Subscription Details',
        'sub.list.view.user': 'User',
        'sub.list.view.plan': 'Plan',
        'sub.list.view.amount': 'Amount',
        'sub.list.view.status': 'Status',
        'sub.list.view.paymentMethod': 'Payment Method',
        'sub.list.view.reference': 'Reference',
        'sub.list.view.created': 'Created',
        'sub.list.view.startDate': 'Start Date',
        'sub.list.view.expiryDate': 'Expiry Date',
        'sub.list.view.adminNotes': 'Admin Notes',
        'sub.list.view.invoice': 'Invoice',
        'sub.list.view.invoiceNumber': 'Number',
        'sub.list.view.invoiceStatus': 'Status',
        'sub.list.view.invoiceAmount': 'Amount',
    },

    sw: {
        // ── Common ────────────────────────────────────────────────
        'sub.common.cancel': 'Ghairi',
        'sub.common.confirm': 'Thibitisha',
        'sub.common.close': 'Funga',
        'sub.common.delete': 'Futa',
        'sub.common.deleting': 'Inafuta…',
        'sub.common.update': 'Sasisha',
        'sub.common.create': 'Unda',
        'sub.common.edit': 'Hariri',
        'sub.common.active': 'Hai',
        'sub.common.inactive': 'Haipo',
        'sub.common.areYouSure': 'Una uhakika?',
        'sub.common.cannotUndo': 'Kitendo hiki hakiwezi kutenduliwa.',
        'sub.common.actions': 'Vitendo',
        'sub.common.status': 'Hali',
        'sub.common.name': 'Jina',
        'sub.common.phone': 'Simu',
        'sub.common.order': 'Mpangilio',
        'sub.common.search': 'Tafuta',
        'sub.common.refresh': 'Onyesha Upya',
        'sub.common.all': 'Zote',

        // ── Payment Methods ───────────────────────────────────────
        'sub.pm.accessDenied': 'Unahitaji ruhusa kusimamia njia za malipo.',
        'sub.pm.title': 'Njia za Malipo',
        'sub.pm.subtitle': 'Simamia chaguo za malipo zinazopatikana kwa watumiaji',
        'sub.pm.totalMethods': 'Jumla ya Njia',
        'sub.pm.active': 'Hai',
        'sub.pm.inactive': 'Haipo',
        'sub.pm.searchPlaceholder': 'Tafuta njia…',
        'sub.pm.addMethod': 'Ongeza Njia',
        'sub.pm.col.logo': 'Nembo',
        'sub.pm.col.name': 'Jina',
        'sub.pm.col.phone': 'Simu',
        'sub.pm.col.account': 'Akaunti',
        'sub.pm.col.status': 'Hali',
        'sub.pm.col.order': 'Mpangilio',
        'sub.pm.col.actions': 'Vitendo',
        'sub.pm.noMatch': 'Hakuna njia za malipo zinazolingana na utafutaji wako',
        'sub.pm.noFound': 'Hakuna njia za malipo zilizopatikana',
        'sub.pm.editTooltip': 'Hariri',
        'sub.pm.deleteTooltip': 'Futa',
        'sub.pm.form.editTitle': 'Hariri Njia ya Malipo',
        'sub.pm.form.createTitle': 'Unda Njia Mpya ya Malipo',
        'sub.pm.form.editDesc': 'Sasisha maelezo ya njia ya malipo',
        'sub.pm.form.createDesc': 'Ongeza chaguo jipya la malipo',
        'sub.pm.form.name': 'Jina *',
        'sub.pm.form.phoneNumber': 'Namba ya Simu *',
        'sub.pm.form.accountName': 'Jina la Akaunti',
        'sub.pm.form.displayOrder': 'Mpangilio wa Kuonyesha',
        'sub.pm.form.uploadLogo': 'Pakia Nembo',
        'sub.pm.form.logoSelected': 'imechaguliwa',
        'sub.pm.delete.title': 'Futa Njia ya Malipo',
        'sub.pm.delete.aboutTo': 'Unakaribia kufuta njia ya malipo:',
        'sub.pm.delete.warning': 'Data yote inayohusiana na njia hii ya malipo itaondolewa kabisa.',

        // ── Rate Cards ────────────────────────────────────────────
        'sub.rc.accessDenied': 'Unahitaji ruhusa kusimamia kadi za viwango.',
        'sub.rc.title': 'Kadi za Viwango',
        'sub.rc.subtitle': 'Simamia mipango ya usajili na bei',
        'sub.rc.totalCards': 'Jumla ya Kadi',
        'sub.rc.active': 'Hai',
        'sub.rc.inactive': 'Haipo',
        'sub.rc.searchPlaceholder': 'Tafuta kadi za viwango…',
        'sub.rc.addCard': 'Ongeza Kadi ya Kiwango',
        'sub.rc.col.name': 'Jina',
        'sub.rc.col.price': 'Bei',
        'sub.rc.col.duration': 'Muda',
        'sub.rc.col.currency': 'Sarafu',
        'sub.rc.col.status': 'Hali',
        'sub.rc.col.order': 'Mpangilio',
        'sub.rc.col.actions': 'Vitendo',
        'sub.rc.days': 'siku',
        'sub.rc.noMatch': 'Hakuna kadi za viwango zinazolingana na utafutaji wako',
        'sub.rc.noFound': 'Hakuna kadi za viwango zilizopatikana',
        'sub.rc.editTooltip': 'Hariri',
        'sub.rc.deleteTooltip': 'Futa',
        'sub.rc.form.editTitle': 'Hariri Kadi ya Kiwango',
        'sub.rc.form.createTitle': 'Unda Kadi Mpya ya Kiwango',
        'sub.rc.form.editDesc': 'Sasisha maelezo ya mpango',
        'sub.rc.form.createDesc': 'Eleza mpango mpya wa usajili',
        'sub.rc.form.name': 'Jina *',
        'sub.rc.form.price': 'Bei *',
        'sub.rc.form.currency': 'Sarafu *',
        'sub.rc.form.duration': 'Muda (siku) *',
        'sub.rc.form.description': 'Maelezo',
        'sub.rc.form.displayOrder': 'Mpangilio wa Kuonyesha',
        'sub.rc.form.active': 'Hai',
        'sub.rc.delete.title': 'Futa Kadi ya Kiwango',
        'sub.rc.delete.aboutTo': 'Unakaribia kufuta kadi ya kiwango:',
        'sub.rc.delete.warning': 'Data yote inayohusiana na kadi hii ya kiwango itaondolewa kabisa.',

        // ── Subscription List ─────────────────────────────────────
        'sub.list.accessDenied': 'Huna ruhusa.',
        'sub.list.title': 'Usajili',
        'sub.list.subtitle': 'Simamia na kuidhinisha usajili wa watumiaji',
        'sub.list.pending': 'Inasubiri',
        'sub.list.active': 'Hai',
        'sub.list.expired': 'Imekwisha',
        'sub.list.cancelled': 'Imefutwa',
        'sub.list.searchPlaceholder': 'Tafuta…',
        'sub.list.filters': 'Vichujio',
        'sub.list.dateFrom': 'Tarehe Kutoka',
        'sub.list.dateTo': 'Tarehe Hadi',
        'sub.list.apply': 'Tumia',
        'sub.list.clear': 'Safisha',
        'sub.list.noFound': 'Hakuna usajili uliopatikana',
        'sub.list.col.user': 'Mtumiaji',
        'sub.list.col.plan': 'Mpango',
        'sub.list.col.amount': 'Kiasi',
        'sub.list.col.status': 'Hali',
        'sub.list.col.paymentMethod': 'Njia ya Malipo',
        'sub.list.col.reference': 'Kumbukumbu',
        'sub.list.col.date': 'Tarehe',
        'sub.list.col.expiry': 'Kuisha',
        'sub.list.col.actions': 'Vitendo',
        'sub.list.status.pending': 'Inasubiri',
        'sub.list.status.active': 'Hai',
        'sub.list.status.expired': 'Imekwisha',
        'sub.list.status.cancelled': 'Imefutwa',
        'sub.list.export.csv': 'CSV',
        'sub.list.export.pdf': 'PDF',
        'sub.list.export.excel': 'Excel',

        // Messages
        'sub.list.msg.loadFailed': 'Imeshindwa kupakia usajili',
        'sub.list.msg.noInvoice': 'Hakuna ankara inayopatikana',
        'sub.list.msg.invoiceDownloaded': 'Ankara imepakuliwa kwa mafanikio',
        'sub.list.msg.invoiceOpened': 'Ankara imefunguliwa kwenye kichupo kipya',
        'sub.list.msg.invoiceFailed': 'Imeshindwa kupakua ankara',
        'sub.list.msg.approved': 'Usajili #{id} umeidhinishwa kwa mafanikio!',
        'sub.list.msg.approveFailed': 'Uidhinishaji umeshindikana: {msg}',
        'sub.list.msg.rejected': 'Usajili #{id} umekataliwa',
        'sub.list.msg.rejectFailed': 'Ukatali umeshindikana',

        // Actions
        'sub.list.action.approve': 'Idhinisha',
        'sub.list.action.reject': 'Kataa',
        'sub.list.action.viewDetails': 'Ona Maelezo',
        'sub.list.action.downloadInvoice': 'Pakua Ankara',
        'sub.list.action.invoice': 'Ankara',
        'sub.list.action.details': 'Maelezo',

        // Reject dialog
        'sub.list.reject.title': 'Kataa Usajili',
        'sub.list.reject.reason': 'Sababu (si lazima)',
        'sub.list.reject.placeholder': 'Weka sababu ya kukataa…',

        // Approve dialog
        'sub.list.approve.confirmTitle': 'Thibitisha Uidhinishaji',
        'sub.list.approve.successTitle': 'Imeidhinishwa kwa Mafanikio!',
        'sub.list.approve.errorTitle': 'Uidhinishaji Umeshindikana',
        'sub.list.approve.subscriptionNo': 'Usajili #{id}',
        'sub.list.approve.infoAlert': 'Unakaribia kuidhinisha usajili huu. Mtumiaji atapata ufikiaji mara moja.',
        'sub.list.approve.unknownUser': 'Mtumiaji Asiyefahamika',
        'sub.list.approve.noEmail': 'Hakuna barua pepe',
        'sub.list.approve.plan': 'Mpango',
        'sub.list.approve.amount': 'Kiasi',
        'sub.list.approve.paymentMethod': 'Njia ya Malipo',
        'sub.list.approve.reference': 'Kumbukumbu',
        'sub.list.approve.processing': 'Inachakata…',
        'sub.list.approve.complete': 'Imekamilika!',
        'sub.list.approve.confirmBtn': 'Thibitisha Uidhinishaji',
        'sub.list.approve.doneBtn': 'Sawa',
        'sub.list.approve.retryBtn': 'Jaribu Tena',
        'sub.list.approve.validating': 'Inathibitisha usajili...',
        'sub.list.approve.processingPayment': 'Inachakata uthibitisho wa malipo...',
        'sub.list.approve.updatingStatus': 'Inasasisha hali ya usajili...',
        'sub.list.approve.generatingInvoice': 'Inatengeneza ankara...',
        'sub.list.approve.sendingNotification': 'Inatuma arifa...',
        'sub.list.approve.successMsg': '{name} anaweza sasa kufikia vipengele vyote.',
        'sub.list.approve.errorDefault': 'Hitilafu imetokea wakati wa kuidhinisha usajili.',

        // View details dialog
        'sub.list.view.title': 'Maelezo ya Usajili',
        'sub.list.view.user': 'Mtumiaji',
        'sub.list.view.plan': 'Mpango',
        'sub.list.view.amount': 'Kiasi',
        'sub.list.view.status': 'Hali',
        'sub.list.view.paymentMethod': 'Njia ya Malipo',
        'sub.list.view.reference': 'Kumbukumbu',
        'sub.list.view.created': 'Imeundwa',
        'sub.list.view.startDate': 'Tarehe ya Kuanza',
        'sub.list.view.expiryDate': 'Tarehe ya Kuisha',
        'sub.list.view.adminNotes': 'Maelezo ya Msimamizi',
        'sub.list.view.invoice': 'Ankara',
        'sub.list.view.invoiceNumber': 'Namba',
        'sub.list.view.invoiceStatus': 'Hali',
        'sub.list.view.invoiceAmount': 'Kiasi',
    },
};

export function tSub(language, key, replacements) {
    let str =
        subscriptionTranslations[language]?.[key] ||
        subscriptionTranslations.en?.[key] ||
        key;
    if (replacements) {
        Object.entries(replacements).forEach(([k, v]) => {
            str = str.replace(new RegExp(`\\{${k}\\}`, 'g'), v);
        });
    }
    return str;
}