// src/pages/monitoring/monitoringlang.js

export const monitoringTranslations = {
    en: {
        // ── Common ────────────────────────────────────────────────
        'mon.common.all': 'All',
        'mon.common.close': 'Close',
        'mon.common.cancel': 'Cancel',
        'mon.common.update': 'Update',
        'mon.common.retry': 'Retry',
        'mon.common.refresh': 'Refresh',
        'mon.common.loading': 'Loading…',
        'mon.common.call': 'Call',
        'mon.common.whatsapp': 'WhatsApp',
        'mon.common.status': 'Status',
        'mon.common.service': 'Service',
        'mon.common.description': 'Description',
        'mon.common.customer': 'Customer',
        'mon.common.technician': 'Technician',
        'mon.common.unknown': 'Unknown',
        'mon.common.unknownCustomer': 'Unknown Customer',
        'mon.common.noPhone': 'No phone',
        'mon.common.noArea': 'No area',
        'mon.common.noDescription': 'No description',
        'mon.common.online': 'Online',
        'mon.common.offline': 'Offline',
        'mon.common.noTechnicianAssigned': 'No technician assigned',
        'mon.common.noTechnicianAssignedYet': 'No technician assigned yet',

        // ── Status labels ─────────────────────────────────────────
        'mon.status.pending': 'Pending',
        'mon.status.accepted': 'Accepted',
        'mon.status.rejected': 'Rejected',
        'mon.status.cancelled': 'Cancelled',
        'mon.status.in_progress': 'In Progress',
        'mon.status.completed': 'Completed',
        'mon.status.timeout': 'Timeout',
        'mon.status.on_the_way': 'On the Way',
        'mon.status.arrived': 'Arrived',

        // ── Dashboard ─────────────────────────────────────────────
        'mon.dash.accessDenied': 'You do not have permission to view the monitoring dashboard.',
        'mon.dash.title': '📊 Monitoring Dashboard',
        'mon.dash.autoRefreshOn': '🔄 Auto-refresh ON',
        'mon.dash.autoRefreshOff': '⏸️ Auto-refresh OFF',
        'mon.dash.refresh': 'Refresh',
        'mon.dash.todayLine': 'Today: {date} • {count} requests today',

        // Stats cards
        'mon.dash.stat.todayRequests': "Today's Requests",
        'mon.dash.stat.pending': 'Pending',
        'mon.dash.stat.timeout': '⚠️ Timeout',
        'mon.dash.stat.accepted': 'Accepted',
        'mon.dash.stat.inProgress': 'In Progress',
        'mon.dash.stat.completed': 'Completed',

        // Alerts
        'mon.dash.alerts': '🔔 Alerts ({count})',
        'mon.dash.alertTimeout': '⚠️ #{id} - {min}m waiting',
        'mon.dash.alertNew': '📌 #{id} - {name}',

        // Filters
        'mon.dash.searchPlaceholder': "Search today's requests...",
        'mon.dash.filter.status': 'Status',
        'mon.dash.filter.mapFilter': 'Map Filter',
        'mon.dash.filter.all': 'All',
        'mon.dash.filter.pending': 'Pending',
        'mon.dash.filter.timeout': '⚠️ Timeout',
        'mon.dash.filter.accepted': 'Accepted',
        'mon.dash.filter.rejected': 'Rejected',
        'mon.dash.filter.inProgress': 'In Progress',
        'mon.dash.filter.completed': 'Completed',
        'mon.dash.filter.mapAll': 'All',
        'mon.dash.filter.mapPending': '🔴 Pending',
        'mon.dash.filter.mapAccepted': '🟢 Accepted',
        'mon.dash.showingLine': 'Showing {shown} requests today • {map} on map',
        'mon.dash.clearFilters': 'Clear Filters',

        // Map section
        'mon.dash.map.title': "🗺️ Today's Requests",
        'mon.dash.map.pending': '{n} Pending',
        'mon.dash.map.accepted': '{n} Accepted',
        'mon.dash.map.timeout': '⚠️ {n} Timeout',
        'mon.dash.map.recenter': 'Recenter map',
        'mon.dash.map.legendPending': 'Pending',
        'mon.dash.map.legendAccepted': 'Accepted',
        'mon.dash.map.legendWaiting': 'Waiting 5+ min',

        // Table section
        'mon.dash.table.title': "📋 Today's Requests ({count})",
        'mon.dash.table.updatedAt': 'Updated {time}',
        'mon.dash.table.noRequests': 'No requests found for today',
        'mon.dash.table.id': 'ID',
        'mon.dash.table.customer': 'Customer',
        'mon.dash.table.service': 'Service',
        'mon.dash.table.status': 'Status',
        'mon.dash.table.time': 'Time',
        'mon.dash.table.actions': 'Actions',
        'mon.dash.table.totalLine': 'Total: {n} requests today',
        'mon.dash.table.viewDetails': 'View Details',
        'mon.dash.table.callTechnician': 'Call Technician',
        'mon.dash.table.updateStatus': 'Update Status',
        'mon.dash.table.minutes': '{m} min',

        // Scroll to top
        'mon.dash.scrollTop': 'Scroll to top',

        // Request detail dialog
        'mon.dash.detail.title': 'Request #{id}',
        'mon.dash.detail.description': 'Description',
        'mon.dash.detail.status': 'Status',
        'mon.dash.detail.created': 'Created',
        'mon.dash.detail.customer': 'Customer',
        'mon.dash.detail.technician': 'Technician',
        'mon.dash.detail.noPhone': 'No phone',
        'mon.dash.detail.noArea': 'No area',

        // Status dialog
        'mon.dash.statusDialog.title': 'Update Status',
        'mon.dash.statusDialog.newStatus': 'New Status',
        'mon.dash.statusDialog.notes': 'Notes',
        'mon.dash.statusDialog.accepted': '✅ Accepted',
        'mon.dash.statusDialog.rejected': '❌ Rejected',
        'mon.dash.statusDialog.inProgress': '⏳ In Progress',
        'mon.dash.statusDialog.completed': '✅ Completed',

        // Call dialog
        'mon.dash.callDialog.title': 'Call Technician',

        // Marker drawer
        'mon.dash.marker.waiting': 'Waiting {m} minutes',
        'mon.dash.marker.service': 'Service',
        'mon.dash.marker.description': 'Description',
        'mon.dash.marker.customer': 'Customer',
        'mon.dash.marker.technician': 'Technician',
        'mon.dash.marker.accept': 'Accept',
        'mon.dash.marker.reject': 'Reject',

        // Toast
        'mon.dash.toast.statusUpdated': 'Status updated successfully',
        'mon.dash.toast.statusUpdateFailed': 'Failed to update status',
        'mon.dash.toast.callFailed': 'Failed to get call details',
        'mon.dash.toast.accepted': 'Request #{id} accepted',
        'mon.dash.toast.acceptFailed': 'Failed to accept',
        'mon.dash.toast.rejected': 'Request #{id} rejected',
        'mon.dash.toast.rejectFailed': 'Failed to reject',

        // ── Map page ──────────────────────────────────────────────
        'mon.map.accessDenied': 'You do not have permission to view the monitoring map.',
        'mon.map.loadFailed': 'Failed to load map data',
        'mon.map.title': '🗺️ Monitoring',
        'mon.map.filter': 'Filter',
        'mon.map.filterAll': 'All',
        'mon.map.filterPending': '🔴 Pending',
        'mon.map.filterAccepted': '🟢 Accepted',
        'mon.map.filterOnTheWay': '🟠 On the Way',
        'mon.map.filterArrived': '🟣 Arrived',
        'mon.map.filterInProgress': '🟣 In Progress',
        'mon.map.filterCompleted': '🔵 Completed',
        'mon.map.chipTotal': 'Total: {n}',
        'mon.map.chipPending': 'Pending: {n}',
        'mon.map.chipAccepted': 'Accepted: {n}',
        'mon.map.chipOnWay': 'On Way: {n}',
        'mon.map.chipArrived': 'Arrived: {n}',
        'mon.map.chipCompleted': 'Completed: {n}',
        'mon.map.fullscreen': 'Fullscreen',
        'mon.map.exitFullscreen': 'Exit Fullscreen',
        'mon.map.retry': 'Retry',
        'mon.map.calculatingRoute': 'Calculating route…',
        'mon.map.kmRoad': '{km} km (road)',
        'mon.map.min': '{n} min',
        'mon.map.directLine': '⚠️ Direct line',
        'mon.map.kmLive': '{km} km live',
        'mon.map.eta': '· ETA {n} min',
        'mon.map.zoomIn': 'Zoom in',
        'mon.map.zoomOut': 'Zoom out',
        'mon.map.recenter': 'Recenter / Fit All',
        'mon.map.legendPending': 'Pending',
        'mon.map.legendAccepted': 'Accepted',
        'mon.map.legendOnWay': 'On the Way',
        'mon.map.legendArrived': 'Arrived',
        'mon.map.legendCompleted': 'Completed',
        'mon.map.legendWaiting': 'Waiting 5+ min',
        'mon.map.legendRoute': 'Route',
        'mon.map.legendLiveGps': 'Live GPS',
        'mon.map.detail.title': 'Request #{id}',
        'mon.map.detail.customer': '👤 Customer',
        'mon.map.detail.technician': '🔧 Technician',
        'mon.map.detail.live': 'LIVE',
        'mon.map.detail.description': 'Description',
        'mon.map.detail.noDescription': 'No description',
        'mon.map.detail.customerPhone': '📞 {phone}',
        'mon.map.detail.customerArea': '📍 {area}',
        'mon.map.detail.locationNA': 'Location not available',
        'mon.map.detail.techArea': '📍 {area}',
        'mon.map.detail.techPhone': '📞 {phone}',
        'mon.map.detail.areaNotSet': 'Area not set',
        'mon.map.detail.routeCalc': 'Calculating route…',
        'mon.map.detail.directLine': '⚠️ Direct line (no road data)',
        'mon.map.detail.kmRoadEta': '{km} km (road) · {min} min ETA',
        'mon.map.detail.kmLive': '{km} km live (straight-line)',
        'mon.map.detail.kmLiveEta': '{km} km live (straight-line) · ETA ~{min} min',
        'mon.map.detail.lastGpsUpdate': 'Last GPS update: {time}',
        'mon.map.call.title': 'Call Technician',
        'mon.map.toast.callFailed': 'Failed to get call details',
        'mon.map.toast.trackingFailed': 'Failed to fetch tracking data',

        // ── Notification Bell ─────────────────────────────────────
        'mon.bell.ariaLabel': 'notifications',
        'mon.bell.title': 'Notifications',
        'mon.bell.refresh': 'Refresh',
        'mon.bell.loading': 'Loading...',
        'mon.bell.pendingRequests': '{n} pending request{s} today',
        'mon.bell.autoRefreshOn': '🔄 Auto-refresh ON',
        'mon.bell.autoRefreshOff': '⏸️ Auto-refresh OFF',
        'mon.bell.allCaughtUp': 'All caught up!',
        'mon.bell.noPending': 'No pending requests at the moment',
        'mon.bell.urgent': 'URGENT',
        'mon.bell.waitingMin': '⚠️ Waiting {m} min',
        'mon.bell.minAgo': '⏳ {m} min ago',
        'mon.bell.customerFallback': 'Customer',
        'mon.bell.serviceFallback': 'Service Request',
        'mon.bell.loadFailed': 'Failed to load notifications',
    },

    sw: {
        // ── Common ────────────────────────────────────────────────
        'mon.common.all': 'Zote',
        'mon.common.close': 'Funga',
        'mon.common.cancel': 'Ghairi',
        'mon.common.update': 'Sasisha',
        'mon.common.retry': 'Jaribu Tena',
        'mon.common.refresh': 'Onyesha Upya',
        'mon.common.loading': 'Inapakia…',
        'mon.common.call': 'Piga Simu',
        'mon.common.whatsapp': 'WhatsApp',
        'mon.common.status': 'Hali',
        'mon.common.service': 'Huduma',
        'mon.common.description': 'Maelezo',
        'mon.common.customer': 'Mteja',
        'mon.common.technician': 'Fundi',
        'mon.common.unknown': 'Haijulikani',
        'mon.common.unknownCustomer': 'Mteja Asiyefahamika',
        'mon.common.noPhone': 'Hakuna simu',
        'mon.common.noArea': 'Hakuna eneo',
        'mon.common.noDescription': 'Hakuna maelezo',
        'mon.common.online': 'Mtandaoni',
        'mon.common.offline': 'Nje ya mtandao',
        'mon.common.noTechnicianAssigned': 'Hakuna fundi aliyepangiwa',
        'mon.common.noTechnicianAssignedYet': 'Hakuna fundi aliyepangiwa bado',

        // ── Status labels ─────────────────────────────────────────
        'mon.status.pending': 'Inasubiri',
        'mon.status.accepted': 'Imekubaliwa',
        'mon.status.rejected': 'Imekataliwa',
        'mon.status.cancelled': 'Imefutwa',
        'mon.status.in_progress': 'Inaendelea',
        'mon.status.completed': 'Imekamilika',
        'mon.status.timeout': 'Muda Umeisha',
        'mon.status.on_the_way': 'Njiani',
        'mon.status.arrived': 'Amefika',

        // ── Dashboard ─────────────────────────────────────────────
        'mon.dash.accessDenied': 'Huna ruhusa kuona dashibodi ya ufuatiliaji.',
        'mon.dash.title': '📊 Dashibodi ya Ufuatiliaji',
        'mon.dash.autoRefreshOn': '🔄 Usasishaji wa Kiotomatiki UMEWASHWA',
        'mon.dash.autoRefreshOff': '⏸️ Usasishaji wa Kiotomatiki UMEZIMWA',
        'mon.dash.refresh': 'Onyesha Upya',
        'mon.dash.todayLine': 'Leo: {date} • maombi {count} leo',

        // Stats cards
        'mon.dash.stat.todayRequests': 'Maombi ya Leo',
        'mon.dash.stat.pending': 'Inasubiri',
        'mon.dash.stat.timeout': '⚠️ Muda Umeisha',
        'mon.dash.stat.accepted': 'Imekubaliwa',
        'mon.dash.stat.inProgress': 'Inaendelea',
        'mon.dash.stat.completed': 'Imekamilika',

        // Alerts
        'mon.dash.alerts': '🔔 Tahadhari ({count})',
        'mon.dash.alertTimeout': '⚠️ #{id} - dakika {min} zinasubiri',
        'mon.dash.alertNew': '📌 #{id} - {name}',

        // Filters
        'mon.dash.searchPlaceholder': 'Tafuta maombi ya leo...',
        'mon.dash.filter.status': 'Hali',
        'mon.dash.filter.mapFilter': 'Kichujio cha Ramani',
        'mon.dash.filter.all': 'Zote',
        'mon.dash.filter.pending': 'Inasubiri',
        'mon.dash.filter.timeout': '⚠️ Muda Umeisha',
        'mon.dash.filter.accepted': 'Imekubaliwa',
        'mon.dash.filter.rejected': 'Imekataliwa',
        'mon.dash.filter.inProgress': 'Inaendelea',
        'mon.dash.filter.completed': 'Imekamilika',
        'mon.dash.filter.mapAll': 'Zote',
        'mon.dash.filter.mapPending': '🔴 Inasubiri',
        'mon.dash.filter.mapAccepted': '🟢 Imekubaliwa',
        'mon.dash.showingLine': 'Inaonyesha maombi {shown} leo • {map} kwenye ramani',
        'mon.dash.clearFilters': 'Safisha Vichujio',

        // Map section
        'mon.dash.map.title': '🗺️ Maombi ya Leo',
        'mon.dash.map.pending': '{n} Inasubiri',
        'mon.dash.map.accepted': '{n} Imekubaliwa',
        'mon.dash.map.timeout': '⚠️ {n} Muda Umeisha',
        'mon.dash.map.recenter': 'Weka ramani katikati',
        'mon.dash.map.legendPending': 'Inasubiri',
        'mon.dash.map.legendAccepted': 'Imekubaliwa',
        'mon.dash.map.legendWaiting': 'Inasubiri dakika 5+',

        // Table section
        'mon.dash.table.title': '📋 Maombi ya Leo ({count})',
        'mon.dash.table.updatedAt': 'Imesasishwa {time}',
        'mon.dash.table.noRequests': 'Hakuna maombi yaliyopatikana kwa leo',
        'mon.dash.table.id': 'Kitambulisho',
        'mon.dash.table.customer': 'Mteja',
        'mon.dash.table.service': 'Huduma',
        'mon.dash.table.status': 'Hali',
        'mon.dash.table.time': 'Muda',
        'mon.dash.table.actions': 'Vitendo',
        'mon.dash.table.totalLine': 'Jumla: maombi {n} leo',
        'mon.dash.table.viewDetails': 'Ona Maelezo',
        'mon.dash.table.callTechnician': 'Piga Fundi',
        'mon.dash.table.updateStatus': 'Sasisha Hali',
        'mon.dash.table.minutes': 'dakika {m}',

        // Scroll to top
        'mon.dash.scrollTop': 'Nenda juu',

        // Request detail dialog
        'mon.dash.detail.title': 'Ombi #{id}',
        'mon.dash.detail.description': 'Maelezo',
        'mon.dash.detail.status': 'Hali',
        'mon.dash.detail.created': 'Imeundwa',
        'mon.dash.detail.customer': 'Mteja',
        'mon.dash.detail.technician': 'Fundi',
        'mon.dash.detail.noPhone': 'Hakuna simu',
        'mon.dash.detail.noArea': 'Hakuna eneo',

        // Status dialog
        'mon.dash.statusDialog.title': 'Sasisha Hali',
        'mon.dash.statusDialog.newStatus': 'Hali Mpya',
        'mon.dash.statusDialog.notes': 'Maelezo',
        'mon.dash.statusDialog.accepted': '✅ Imekubaliwa',
        'mon.dash.statusDialog.rejected': '❌ Imekataliwa',
        'mon.dash.statusDialog.inProgress': '⏳ Inaendelea',
        'mon.dash.statusDialog.completed': '✅ Imekamilika',

        // Call dialog
        'mon.dash.callDialog.title': 'Piga Fundi',

        // Marker drawer
        'mon.dash.marker.waiting': 'Inasubiri dakika {m}',
        'mon.dash.marker.service': 'Huduma',
        'mon.dash.marker.description': 'Maelezo',
        'mon.dash.marker.customer': 'Mteja',
        'mon.dash.marker.technician': 'Fundi',
        'mon.dash.marker.accept': 'Kubali',
        'mon.dash.marker.reject': 'Kataa',

        // Toast
        'mon.dash.toast.statusUpdated': 'Hali imesasishwa kwa mafanikio',
        'mon.dash.toast.statusUpdateFailed': 'Imeshindwa kusasisha hali',
        'mon.dash.toast.callFailed': 'Imeshindwa kupata maelezo ya simu',
        'mon.dash.toast.accepted': 'Ombi #{id} limekubaliwa',
        'mon.dash.toast.acceptFailed': 'Imeshindwa kukubali',
        'mon.dash.toast.rejected': 'Ombi #{id} limekataliwa',
        'mon.dash.toast.rejectFailed': 'Imeshindwa kukataa',

        // ── Map page ──────────────────────────────────────────────
        'mon.map.accessDenied': 'Huna ruhusa kuona ramani ya ufuatiliaji.',
        'mon.map.loadFailed': 'Imeshindwa kupakia data ya ramani',
        'mon.map.title': '🗺️ Ufuatiliaji',
        'mon.map.filter': 'Kichujio',
        'mon.map.filterAll': 'Zote',
        'mon.map.filterPending': '🔴 Inasubiri',
        'mon.map.filterAccepted': '🟢 Imekubaliwa',
        'mon.map.filterOnTheWay': '🟠 Njiani',
        'mon.map.filterArrived': '🟣 Amefika',
        'mon.map.filterInProgress': '🟣 Inaendelea',
        'mon.map.filterCompleted': '🔵 Imekamilika',
        'mon.map.chipTotal': 'Jumla: {n}',
        'mon.map.chipPending': 'Inasubiri: {n}',
        'mon.map.chipAccepted': 'Imekubaliwa: {n}',
        'mon.map.chipOnWay': 'Njiani: {n}',
        'mon.map.chipArrived': 'Amefika: {n}',
        'mon.map.chipCompleted': 'Imekamilika: {n}',
        'mon.map.fullscreen': 'Skrini Kamili',
        'mon.map.exitFullscreen': 'Ondoa Skrini Kamili',
        'mon.map.retry': 'Jaribu Tena',
        'mon.map.calculatingRoute': 'Inahesabu njia…',
        'mon.map.kmRoad': '{km} km (barabara)',
        'mon.map.min': 'dakika {n}',
        'mon.map.directLine': '⚠️ Mstari wa moja kwa moja',
        'mon.map.kmLive': '{km} km moja kwa moja',
        'mon.map.eta': '· ETA dakika {n}',
        'mon.map.zoomIn': 'Kuza',
        'mon.map.zoomOut': 'Punguza',
        'mon.map.recenter': 'Weka Katikati / Onyesha Zote',
        'mon.map.legendPending': 'Inasubiri',
        'mon.map.legendAccepted': 'Imekubaliwa',
        'mon.map.legendOnWay': 'Njiani',
        'mon.map.legendArrived': 'Amefika',
        'mon.map.legendCompleted': 'Imekamilika',
        'mon.map.legendWaiting': 'Inasubiri dakika 5+',
        'mon.map.legendRoute': 'Njia',
        'mon.map.legendLiveGps': 'GPS Moja kwa Moja',
        'mon.map.detail.title': 'Ombi #{id}',
        'mon.map.detail.customer': '👤 Mteja',
        'mon.map.detail.technician': '🔧 Fundi',
        'mon.map.detail.live': 'MOJA KWA MOJA',
        'mon.map.detail.description': 'Maelezo',
        'mon.map.detail.noDescription': 'Hakuna maelezo',
        'mon.map.detail.customerPhone': '📞 {phone}',
        'mon.map.detail.customerArea': '📍 {area}',
        'mon.map.detail.locationNA': 'Eneo halipatikani',
        'mon.map.detail.techArea': '📍 {area}',
        'mon.map.detail.techPhone': '📞 {phone}',
        'mon.map.detail.areaNotSet': 'Eneo halijawekwa',
        'mon.map.detail.routeCalc': 'Inahesabu njia…',
        'mon.map.detail.directLine': '⚠️ Mstari wa moja kwa moja (hakuna data ya barabara)',
        'mon.map.detail.kmRoadEta': '{km} km (barabara) · ETA dakika {min}',
        'mon.map.detail.kmLive': '{km} km moja kwa moja',
        'mon.map.detail.kmLiveEta': '{km} km moja kwa moja · ETA ~dakika {min}',
        'mon.map.detail.lastGpsUpdate': 'Sasisho la mwisho la GPS: {time}',
        'mon.map.call.title': 'Piga Fundi',
        'mon.map.toast.callFailed': 'Imeshindwa kupata maelezo ya simu',
        'mon.map.toast.trackingFailed': 'Imeshindwa kupata data ya ufuatiliaji',

        // ── Notification Bell ─────────────────────────────────────
        'mon.bell.ariaLabel': 'arifa',
        'mon.bell.title': 'Arifa',
        'mon.bell.refresh': 'Onyesha Upya',
        'mon.bell.loading': 'Inapakia...',
        'mon.bell.pendingRequests': 'maombi {n} yanasubiri leo',
        'mon.bell.autoRefreshOn': '🔄 Usasishaji wa Kiotomatiki UMEWASHWA',
        'mon.bell.autoRefreshOff': '⏸️ Usasishaji wa Kiotomatiki UMEZIMWA',
        'mon.bell.allCaughtUp': 'Hakuna kitu kipya!',
        'mon.bell.noPending': 'Hakuna maombi yanayosubiri kwa sasa',
        'mon.bell.urgent': 'HARAKA',
        'mon.bell.waitingMin': '⚠️ Inasubiri dakika {m}',
        'mon.bell.minAgo': '⏳ dakika {m} zilizopita',
        'mon.bell.customerFallback': 'Mteja',
        'mon.bell.serviceFallback': 'Ombi la Huduma',
        'mon.bell.loadFailed': 'Imeshindwa kupakia arifa',
    },
};

export function tMon(language, key, replacements) {
    let str =
        monitoringTranslations[language]?.[key] ||
        monitoringTranslations.en?.[key] ||
        key;
    if (replacements) {
        Object.entries(replacements).forEach(([k, v]) => {
            str = str.replace(new RegExp(`\\{${k}\\}`, 'g'), v);
        });
    }
    return str;
}