// src/pages/login/countryCodes.js

export const COUNTRY_CODES = [
    // ─── AFRICA ─────────────────────────────────────────────
    { name: 'Tanzania', code: '+255', flag: '🇹🇿' },
    { name: 'Kenya', code: '+254', flag: '🇰🇪' },
    { name: 'Uganda', code: '+256', flag: '🇺🇬' },
    { name: 'Rwanda', code: '+250', flag: '🇷🇼' },
    { name: 'Burundi', code: '+257', flag: '🇧🇮' },
    { name: 'South Africa', code: '+27', flag: '🇿🇦' },
    { name: 'Nigeria', code: '+234', flag: '🇳🇬' },
    { name: 'Ghana', code: '+233', flag: '🇬🇭' },
    { name: 'Egypt', code: '+20', flag: '🇪🇬' },
    { name: 'Morocco', code: '+212', flag: '🇲🇦' },
    { name: 'Algeria', code: '+213', flag: '🇩🇿' },
    { name: 'Tunisia', code: '+216', flag: '🇹🇳' },
    { name: 'Libya', code: '+218', flag: '🇱🇾' },
    { name: 'Sudan', code: '+249', flag: '🇸🇩' },
    { name: 'South Sudan', code: '+211', flag: '🇸🇸' },
    { name: 'Ethiopia', code: '+251', flag: '🇪🇹' },
    { name: 'Eritrea', code: '+291', flag: '🇪🇷' },
    { name: 'Djibouti', code: '+253', flag: '🇩🇯' },
    { name: 'Somalia', code: '+252', flag: '🇸🇴' },
    { name: 'Comoros', code: '+269', flag: '🇰🇲' },
    { name: 'Mauritius', code: '+230', flag: '🇲🇺' },
    { name: 'Seychelles', code: '+248', flag: '🇸🇨' },
    { name: 'Madagascar', code: '+261', flag: '🇲🇬' },
    { name: 'Mozambique', code: '+258', flag: '🇲🇿' },
    { name: 'Zambia', code: '+260', flag: '🇿🇲' },
    { name: 'Zimbabwe', code: '+263', flag: '🇿🇼' },
    { name: 'Malawi', code: '+265', flag: '🇲🇼' },
    { name: 'Angola', code: '+244', flag: '🇦🇴' },
    { name: 'Namibia', code: '+264', flag: '🇳🇦' },
    { name: 'Botswana', code: '+267', flag: '🇧🇼' },
    { name: 'Eswatini', code: '+268', flag: '🇸🇿' },
    { name: 'Lesotho', code: '+266', flag: '🇱🇸' },
    { name: 'Senegal', code: '+221', flag: '🇸🇳' },
    { name: 'Mali', code: '+223', flag: '🇲🇱' },
    { name: 'Burkina Faso', code: '+226', flag: '🇧🇫' },
    { name: 'Niger', code: '+227', flag: '🇳🇪' },
    { name: 'Chad', code: '+235', flag: '🇹🇩' },
    { name: 'Central African Republic', code: '+236', flag: '🇨🇫' },
    { name: 'Cameroon', code: '+237', flag: '🇨🇲' },
    { name: 'Equatorial Guinea', code: '+240', flag: '🇬🇶' },
    { name: 'Gabon', code: '+241', flag: '🇬🇦' },
    { name: 'Congo', code: '+242', flag: '🇨🇬' },
    { name: 'DR Congo', code: '+243', flag: '🇨🇩' },
    { name: 'São Tomé and Príncipe', code: '+239', flag: '🇸🇹' },
    { name: "Côte d'Ivoire", code: '+225', flag: '🇨🇮' },
    { name: 'Liberia', code: '+231', flag: '🇱🇷' },
    { name: 'Sierra Leone', code: '+232', flag: '🇸🇱' },
    { name: 'Guinea', code: '+224', flag: '🇬🇳' },
    { name: 'Guinea-Bissau', code: '+245', flag: '🇬🇼' },
    { name: 'Cape Verde', code: '+238', flag: '🇨🇻' },
    { name: 'Mauritania', code: '+222', flag: '🇲🇷' },
    { name: 'The Gambia', code: '+220', flag: '🇬🇲' },
    { name: 'Benin', code: '+229', flag: '🇧🇯' },
    { name: 'Togo', code: '+228', flag: '🇹🇬' },


    // ─── AMERICAS ───────────────────────────────────────────
    { name: 'United States', code: '+1', flag: '🇺🇸' },
    { name: 'Canada', code: '+1', flag: '🇨🇦' },
    { name: 'Mexico', code: '+52', flag: '🇲🇽' },
    { name: 'Brazil', code: '+55', flag: '🇧🇷' },
    { name: 'Argentina', code: '+54', flag: '🇦🇷' },
    { name: 'Colombia', code: '+57', flag: '🇨🇴' },
    { name: 'Chile', code: '+56', flag: '🇨🇱' },
    { name: 'Peru', code: '+51', flag: '🇵🇪' },
    { name: 'Venezuela', code: '+58', flag: '🇻🇪' },
    { name: 'Cuba', code: '+53', flag: '🇨🇺' },
    { name: 'Dominican Republic', code: '+1', flag: '🇩🇴' },

    // ─── EUROPE ─────────────────────────────────────────────
    { name: 'United Kingdom', code: '+44', flag: '🇬🇧' },
    { name: 'Germany', code: '+49', flag: '🇩🇪' },
    { name: 'France', code: '+33', flag: '🇫🇷' },
    { name: 'Italy', code: '+39', flag: '🇮🇹' },
    { name: 'Spain', code: '+34', flag: '🇪🇸' },
    { name: 'Portugal', code: '+351', flag: '🇵🇹' },
    { name: 'Netherlands', code: '+31', flag: '🇳🇱' },
    { name: 'Belgium', code: '+32', flag: '🇧🇪' },
    { name: 'Switzerland', code: '+41', flag: '🇨🇭' },
    { name: 'Austria', code: '+43', flag: '🇦🇹' },
    { name: 'Sweden', code: '+46', flag: '🇸🇪' },
    { name: 'Norway', code: '+47', flag: '🇳🇴' },
    { name: 'Denmark', code: '+45', flag: '🇩🇰' },
    { name: 'Finland', code: '+358', flag: '🇫🇮' },
    { name: 'Ireland', code: '+353', flag: '🇮🇪' },
    { name: 'Greece', code: '+30', flag: '🇬🇷' },
    { name: 'Turkey', code: '+90', flag: '🇹🇷' },
    { name: 'Russia', code: '+7', flag: '🇷🇺' },
    { name: 'Ukraine', code: '+380', flag: '🇺🇦' },
    { name: 'Poland', code: '+48', flag: '🇵🇱' },
    { name: 'Czech Republic', code: '+420', flag: '🇨🇿' },
    { name: 'Hungary', code: '+36', flag: '🇭🇺' },
    { name: 'Romania', code: '+40', flag: '🇷🇴' },
    { name: 'Bulgaria', code: '+359', flag: '🇧🇬' },
    { name: 'Serbia', code: '+381', flag: '🇷🇸' },

    // ─── ASIA ───────────────────────────────────────────────
    { name: 'India', code: '+91', flag: '🇮🇳' },
    { name: 'China', code: '+86', flag: '🇨🇳' },
    { name: 'Japan', code: '+81', flag: '🇯🇵' },
    { name: 'South Korea', code: '+82', flag: '🇰🇷' },
    { name: 'Indonesia', code: '+62', flag: '🇮🇩' },
    { name: 'Malaysia', code: '+60', flag: '🇲🇾' },
    { name: 'Singapore', code: '+65', flag: '🇸🇬' },
    { name: 'Philippines', code: '+63', flag: '🇵🇭' },
    { name: 'Vietnam', code: '+84', flag: '🇻🇳' },
    { name: 'Thailand', code: '+66', flag: '🇹🇭' },
    { name: 'Pakistan', code: '+92', flag: '🇵🇰' },
    { name: 'Bangladesh', code: '+880', flag: '🇧🇩' },
    { name: 'Sri Lanka', code: '+94', flag: '🇱🇰' },
    { name: 'Nepal', code: '+977', flag: '🇳🇵' },
    { name: 'Afghanistan', code: '+93', flag: '🇦🇫' },
    { name: 'Uzbekistan', code: '+998', flag: '🇺🇿' },
    { name: 'Kazakhstan', code: '+7', flag: '🇰🇿' },
    { name: 'Saudi Arabia', code: '+966', flag: '🇸🇦' },
    { name: 'United Arab Emirates', code: '+971', flag: '🇦🇪' },
    { name: 'Qatar', code: '+974', flag: '🇶🇦' },
    { name: 'Kuwait', code: '+965', flag: '🇰🇼' },
    { name: 'Oman', code: '+968', flag: '🇴🇲' },
    { name: 'Yemen', code: '+967', flag: '🇾🇪' },
    { name: 'Jordan', code: '+962', flag: '🇯🇴' },
    { name: 'Lebanon', code: '+961', flag: '🇱🇧' },
    { name: 'Israel', code: '+972', flag: '🇮🇱' },
    { name: 'Palestine', code: '+970', flag: '🇵🇸' },
    { name: 'Cyprus', code: '+357', flag: '🇨🇾' },
    { name: 'Georgia', code: '+995', flag: '🇬🇪' },
    { name: 'Armenia', code: '+374', flag: '🇦🇲' },
    { name: 'Azerbaijan', code: '+994', flag: '🇦🇿' },

    // ─── OCEANIA ────────────────────────────────────────────
    { name: 'Australia', code: '+61', flag: '🇦🇺' },
    { name: 'New Zealand', code: '+64', flag: '🇳🇿' },
    { name: 'Papua New Guinea', code: '+675', flag: '🇵🇬' },
    { name: 'Fiji', code: '+679', flag: '🇫🇯' },
    { name: 'Samoa', code: '+685', flag: '🇼🇸' },
    { name: 'Solomon Islands', code: '+677', flag: '🇸🇧' },
    { name: 'Vanuatu', code: '+678', flag: '🇻🇺' },
];