<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $title }}</title>
    <style>
        body { 
            font-family: 'DejaVu Sans', sans-serif; 
            padding: 20px;
        }
        h1 { 
            text-align: center; 
            color: #333;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
        }
        .meta {
            text-align: center;
            color: #666;
            margin-bottom: 30px;
        }
        table { 
            width: 100%; 
            border-collapse: collapse; 
            margin-top: 20px;
            font-size: 12px;
        }
        th { 
            background: #f0f0f0; 
            border: 1px solid #ddd; 
            padding: 8px; 
            text-align: left;
            font-weight: bold;
        }
        td { 
            border: 1px solid #ddd; 
            padding: 8px; 
        }
        tr:nth-child(even) {
            background: #f9f9f9;
        }
        .footer { 
            text-align: center; 
            margin-top: 30px; 
            font-size: 12px; 
            color: #888;
            border-top: 1px solid #ddd;
            padding-top: 20px;
        }
    </style>
</head>
<body>
    <h1>{{ $title }}</h1>
    <div class="meta">Generated: {{ $generated_at }} | Total Records: {{ count($data) }}</div>
    
    <table>
        <thead>
            <tr>
                @foreach($headers as $header)
                    <th>{{ $header }}</th>
                @endforeach
            </tr>
        </thead>
        <tbody>
            @foreach($data as $row)
                <tr>
                    @foreach($row as $value)
                        <td>{{ $value }}</td>
                    @endforeach
                </tr>
            @endforeach
        </tbody>
    </table>
    
    <div class="footer">Generated by {{ config('app.name') }} - {{ now()->format('Y-m-d H:i:s') }}</div>
</body>
</html>